### ISSUE TITLE
Indexed class with no specified subscripts

### ISSUE THREAD

**Issue by BaradaNikto** [wdputro/stage-controller-GUI#1]
Thank you for providing this useful GUI template.  However, you might wish to know that loading the as-shipped application "controllerApp.mlapp" in Matlab R2017b in Windows 7 x64 with a running 64-bit C/C++ compiler (MinGW-w64) yields the following error reports (no changes made to the as-shipped code by the user):

> Warning: A value of class "appdesigner.internal.service.AppManagementService" was indexed
with no subscripts specified. Currently the result of this operation is the indexed value
itself, but in a future release, it will be an error. 
> In matlab.apps.AppBase/registerApp (line 26)
  In controllerApp (line 1291) 
Warning: A value of class "appdesigner.internal.service.AppManagementService" was indexed
with no subscripts specified. Currently the result of this operation is the indexed value
itself, but in a future release, it will be an error. 
> In matlab.apps.AppBase/runStartupFcn (line 22)
  In controllerApp (line 1294) 
Warning: A value of class "appdesigner.internal.service.AppManagementService" was indexed
with no subscripts specified. Currently the result of this operation is the indexed value
itself, but in a future release, it will be an error. 
> In matlab.apps.AppBase/delete (line 7)
  In appdesigner.internal.service.AppManagementService>@(src,e)delete(app) (line 210)
  In closereq (line 18)
  In matlab.ui.internal.controller.FigureController>@(o,e)this.Model.hgclose() (line 239)
  In internal.Callback.execute (line 128)
  In matlab.internal.webwindow/onCustomEvent (line 1055)
  In matlab.internal.webwindow>@(source,data)obj.onCustomEvent(data.Type,data.Data) (line 238)
  In asyncio.Channel/onCustomEvent (line 429)
  In asyncio.Channel>@(source,data)obj.onCustomEvent(data.Type,data.Data) (line 361)

**Comment by BaradaNikto** [comment]
So, MathWorks admits that this is a bug in the current version of Matlab:.  To quote Ijab Zhan of MathWorks:

"This is a warning for MATLAB's future feature change, which is thrown from an internal function. Acknowledge that this is a bug, and it will be fixed in future release.

A workaround for now is to turn off the warning - 'MATLAB:subscripting:noSubscriptsSpecified'. You can do it in the MATLAB Command Window by: warning('off', 'MATLAB:subscripting:noSubscriptsSpecified')."

**Comment by wdputro** [comment]
@BaradaNikto Thanks for the info, hopefully it's already fixed!
